# MES环境配置
http:
  mes:
    host: 'https://c2.xinheyun.com'
    appKey: '4a9456e8-2daa-4292-8376-8240386ac32b'
    appSecret: 'K?0n10|43@d(Ssd>'

  # 畅捷通环境配置
  chanJet:
    host: 'https://openapi.chanjet.com'
    key: '19981020'
    secret: '19981020'
    refreshToken: '19981020'

  # 金蝶K3Wise环境配置  
  k3wise:
    host: ''
    authorityCode: '19981020'

  # 金蝶k3Cloud环境配置
  k3cloud:
    host: ''
    key: ''
    secret: ''
    lcid: 2052
    acctid: '19981020'
